export const SET_ACTIVE_FORM = 'SET_ACTIVE_FORM';
export const SET_ACTIVE_FORM_LOADING = 'SET_ACTIVE_FORM_LOADING';
export const RESET_ACTIVE_FROM = 'RESET_ACTIVE_FROM';

export const SUBMIT_FORM = {
    SUCCESSFUL: 'SUCCESSFUL',
    ERROR: 'ERROR'
};
